### ISSUE TITLE
Tooltip Proptypes reference Element, which can cause SSR issues.

### ISSUE THREAD

**Issue by mattbeck** [puppetlabs/design-system#284]
## Describe the Bug
The Tooltip PropType definition includes a reference to Element that caused a break for us when we updated PDS for puppet.com

https://github.com/puppetlabs/design-system/blob/development/packages/react-components/source/react/library/tooltips/Tooltip.js
```
  target: PropTypes.instanceOf(Element).isRequired,
```

Looks like we can get around this by shimming **Element** in our gatsby-ssr.js to unblock our work - but it should really either not be needed, or if it _is_ needed, any shim/polyfill should be in the node module. We have to do some weird stuff in our Webpack config to make that shim visible to the imported node module.

Alternately, stripping PropTypes from the node module when .../react-components/build/library.js is assembled would probably resolve it.

## Expected Behavior
If Element is used in this way it needs to be defined.

## Steps to Reproduce
Build PDS with an SSR tool (in our case Gatsby) including any PDS component - it triggered for us on Breadcrumb but the error has to do with Tooltip, which we don't even implement.

## Environment
 - Version [5.21.1]
 - Platform [Production builds failed using PDS on local, github actions, and netlify]

## Additional Context

More information about the specific issue in this StackOverflow 
https://stackoverflow.com/questions/48007326/what-is-the-correct-proptype-for-a-ref-in-react/51127130#51127130 (See "Note about server side rendering")

**Comment by mattbeck** [comment]
![Screen Shot 2020-08-19 at 12 36 32 PM](https://user-images.githubusercontent.com/2372870/90681693-a3989600-e218-11ea-9dc4-dcdac7d6b6a5.png)

**Comment by caseywilliams** [comment]
This is an issue on the forge as well
