### ISSUE TITLE
Use "error" icon in "danger" Alert

### ISSUE THREAD

**Issue by jilliankeenan** [puppetlabs/design-system#310]
In `<Alert type="danger">` **below**
![Screenshot 2020-10-01 at 17 54 03](https://user-images.githubusercontent.com/20307965/94839631-25cacb80-040f-11eb-8ed6-1131b80f8abb.png)

 We want to switch the icon being used from 'Alert' to use the 'error' icon located [here](https://puppet.style/#/React%20Components/Icon)

**Comment by sohamsshah** [comment]
I would like to work on this issue. Can you elaborate the task and assign me this? Will complete ASAP.

**Comment by vine77** [comment]
Thanks @sohamsshah for offering to help! Currently, the [Alert](https://puppet.style/#/React%20Components/Alert) component uses the "alert" icon for both `<Alert type="warning">` and `<Alert type="danger">`. We would like to switch the icon for `<Alert type="danger">` to be the "error" icon. (You can see both icons in the full list of icons in the [Icon docs](https://puppet.style/#/React%20Components/Icon).) Feel free to let us know if you have any trouble setting up the development environment.

**Comment by sohamsshah** [comment]
@vine77 On it! Thank you so much for such a great explanation

**Comment by sohamsshah** [comment]
Dear @vine77 I am having issues in setting up the development environment. Getting a couple of errors while doing that in my system.

What steps I followed:
1. Forked and cloned to my system and cd to the design-system/packages/react-components
2. npm install (got error: 'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.)
3.  npm install @puppet/react-components ( got error: code ENOSELF)
4. npm start (got error: Cannot find module 'extract-text-webpack-plugin')
5. So I did: npm i extract-text-webpack-plugin (to get this installed)

But still the same errors persists in above steps. I actually didnt understand the Setup guides fully with clarity. Can you assist with these?
