### ISSUE TITLE
Add avatar image component

### ISSUE THREAD

**Issue by jilliankeenan** [puppetlabs/design-system#311]
Many Puppet products include circularly clipped avatar images - this would be a nice thing to have in the Puppet Design System for anyone wanting this effect without reimplementing it from scratch. 

We technically have something like this embedded in [Sidebar](https://puppet.style/#/React%20Components/Sidebar) in the Sidebar.Footer where an image can be passed in and get a circle around it. 

What we'd like to do is make an **avatar component** that can be used anywhere as well as migrating to using it in **Sidebar.Footer**.

**Comment by sohamsshah** [comment]
Hey can you share the link of the file that can be edited for this feature? I am new to OpenSource and thus finding some issues to get started. Mam if you assist, I would love to be active contributor of this repo and probably can provide value to this awesome project!

**Comment by niftyrinki** [comment]
Working on this

**Comment by vine77** [comment]
Thanks for offering to help! Just wanted to clarify that this will be a new React component, so we'll need a new folder `avatar` in [packages/react-components/source/react/library](https://github.com/puppetlabs/design-system/tree/development/packages/react-components/source/react/library). Feel free to let us know if you have any trouble setting up the development environment.
