### ISSUE TITLE
Housekeeping - slash division in scss is deprecated

### ISSUE THREAD

**Issue by mattbeck** [puppetlabs/design-system#476]
Various components (at least these) are using / to denote division, this is deprecated and threw warnings during builds with newer webpack and dart sass.

These and any others should get updated with sass:math and math.div()

https://github.com/puppetlabs/design-system/blob/main/packages/react-components/source/scss/library/components/_content.scss
https://github.com/puppetlabs/design-system/blob/main/packages/react-components/source/scss/library/components/_tabs.scss
https://github.com/puppetlabs/design-system/blob/main/packages/react-components/source/scss/library/components/_tooltips.scss

**Comment by vine77** [comment]
Fixed in #564
