### ISSUE TITLE
Domain transfer for "puppet.style"?

### ISSUE THREAD

**Issue by geoffnichols** [puppetlabs/design-system#579]
👋 Hello PDS team!  The "puppet.style" domain is registered to my personal Google Domains account. Is there a current Puppet employee who'd like to take over the domain? Not super urgent, since the domain registration expires in March 2023, but I would like to transfer it before the next renewal 📆

**Comment by vine77** [comment]
Hey @geoffnichols! Thanks again for setting that up. Good question about the domain registration. I wonder if the IT team can take ownership...

**Comment by vine77** [comment]
I'll ask

**Comment by vine77** [comment]
@geoffnichols Gene Liverman <gene.liverman@puppet.com> said that you can transfer it to him, after which he will move it to Puppet's normal registrar.

**Comment by geoffnichols** [comment]
Thanks @vine77! I will initiate the domain transfer to @genebean
